Repository RollForGuild/rollforguild.com, pull requests merged in 2018-06, with the labels that each got.

#227 [WEB-113] Fix error when Dropdown isn't mounted immediately
  components/Dropdown.js
Labels: 🐛bugfix

#226 [WEB-114] Convert home page to a Wordpress proxy
  components/Hero.js
  components/Main.js
  package.json
  pages/index.js
  pages/wordpress-proxy.js
  scss/_colors.scss
  scss/_variables.scss
  scss/app.scss
  scss/components/_hero.scss
  scss/lib.scss
  scss/wordpress.scss
  server/config/router.js
  static/slider-revolution/css/slider-revolution.css
  static/slider-revolution/js/jquery-migrate.min.js
  static/slider-revolution/js/jquery.js
  static/slider-revolution/js/jquery.themepunch.revolution.min.js
  static/slider-revolution/js/jquery.themepunch.tools.min.js
  static/slider-revolution/js/revolution.extension.actions.min.js
  static/slider-revolution/js/revolution.extension.carousel.min.js
  static/slider-revolution/js/revolution.extension.kenburn.min.js
  static/slider-revolution/js/revolution.extension.layeranimation.min.js
  static/slider-revolution/js/revolution.extension.migration.min.js
  static/slider-revolution/js/revolution.extension.navigation.min.js
  static/slider-revolution/js/revolution.extension.parallax.min.js
  static/slider-revolution/js/revolution.extension.slideanims.min.js
  static/slider-revolution/js/revolution.extension.video.min.js
  static/slider-revolution/js/slider-revolution.js
  static/slider-revolution/revicons/revicons.eot
  static/slider-revolution/revicons/revicons.svg
  static/slider-revolution/revicons/revicons.ttf
  static/slider-revolution/revicons/revicons.woff
  yarn.lock
Labels: ✨feature

#229 [WEB-154] [WEB-155] Add "infinite" search range
  components/GroupCard.js
  pages/groups/search.js
  scss/components/_dropdown.scss
  store/actions/groups.js
Labels: ✨feature

#228 Wordpress Proxy Rework
  components/AppLayout.js
  components/Nav.js
  components/Page.js
  helpers/connect.js
  pages/about/team.js
  pages/character-builder.js
  pages/character.js
  pages/confirmations/account-confirm.js
  pages/confirmations/email-update-confirm.js
  pages/contact.js
  pages/forgot-password.js
  pages/forums/create.js
  pages/forums/list.js
  pages/forums/view.js
  pages/groups/create.js
  pages/groups/group.js
  pages/groups/search.js
  pages/login.js
  pages/logout.js
  pages/my/character.js
  pages/my/characters.js
  pages/privacy-policy.js
  pages/register.js
  pages/reset-password.js
  pages/roadmap.js
  pages/terms-and-conditions.js
  pages/users/user.js
  pages/wordpress-proxy.js
  routes.js
  server/config/router.js
  store.js
  store/actionCreators.js
  store/actionTypes.js
  store/actions/wordpress.js
  store/initialState.js
  store/reducers/index.js
  store/reducers/wordpress.js
Labels: ⚙️task, ✍️help wanted

#230 Fix invalid group search state, and a couple other things
  components/Component.js
  components/GroupCard.js
  pages/groups/search.js
  store/actions/groups.js
Labels: ☠️urgent, 🐛bugfix

#232 Fix Group Page
  pages/groups/group.js
Labels: ☠️urgent, 🐛bugfix

#233 Release v1.8.9
  pages/groups/group.js
Labels: 📦release

#234 [WEB-156] Fix search result limits
  store/actions/groups.js
Labels: 🐛bugfix

#235 Release v1.8.9
  store/actions/groups.js
Labels: 📦release

#237 Remove superfluous character builder files
  components/AbilityScore.js
  components/AbilityScoreChart.js
  components/AbilityScoreEditor.js
  components/BackgroundChooser/BackgroundChooser.js
  components/BackgroundChooser/BackgroundPropChooser.js
  components/BackgroundChooser/Option.js
  components/CharacterDescriptionEditor.js
  components/CharacterReview.js
  components/Chooser/Chooser.js
  components/Chooser/Option.js
  components/Chooser/OptionAsButton.js
  components/Dropdown.js
  components/RaceAndClassChooser.js
  components/SkillEditor.js
  components/Wizard.js
  docker-compose.yml
  pages/character-builder.js
  pages/character.js
  pages/my/character.js
  pages/my/characters.js
  store.js
  store/actions/characters.js
  store/actions/rulesets.js
  store/reducers/characters.js
  store/reducers/index.js
  store/reducers/rulesets.js
Labels: ⚙️task

#236 [WEB-142] Refactor password requirements
  components/PasswordInput.js
  helpers/faIconLibrary.js
  scss/_colors.scss
  scss/_variables.scss
  scss/app.scss
  scss/colors/_dark-green.scss
  scss/colors/_yellow.scss
  scss/components/_alert-card.scss
  scss/components/_chooser.scss
  scss/components/_error-box.scss
  scss/components/_password-input.scss
  scss/components/_validated-input.scss
  scss/core/_button.scss
  scss/lib.scss
  scss/lib/_rc-slider.scss
  scss/variables/_error.scss
  scss/variables/_info.scss
  scss/variables/_success.scss
  scss/variables/_warn.scss
Labels: ⚙️task, 🐛bugfix

#238 fix(Dropdown): Restore Dropdown component
  components/Dropdown.js
Labels: 🐛bugfix

#239 [WEB-159] Login hanging
  pages/login.js
  scss/wordpress.scss
Labels: 🐛bugfix

#240 [WEB-131] Fix markdown lists
  components/Forums/ForumThreadCard.js
  components/Markdown.js
  scss/app.scss
  scss/components/_markdown.scss
Labels: 🐛bugfix
