Repository RollForGuild/rollforguild.com, pull requests merged in 2018-04, with the labels that each got.

#146 [WEB-82] Fix password reset action method
  store/actions/authentication.js
Labels: ☠️urgent, 🐛bugfix

#147 [WEB-83] Fix account confirmation
  pages/confirmations/account-confirm.js
Labels: ☠️urgent, 🐛bugfix

#148 [WEB-80] Remove games from groups
  components/GroupCard.js
  pages/groups/create.js
  pages/groups/group.js
Labels: ☠️urgent, 🐛bugfix

#149 [WEB-1] Add address string to <StaticMap /> components
  components/StaticMap.js
  scss/components/_static-map.scss
Labels: ✨feature

#151 Docker!
  .env.example
  .vscode/launch.json
  Dockerfile
  README.md
  docker-compose.yml
  package.json
  yarn.lock
Labels: ✨feature

#150 [WEB-49] Thread and Comment deletion
  .eslintignore
  components/Forums/ForumThreadCard.js
  components/Forums/ThreadCommentCard.js
  next.config.js
  pages/forums/list.js
  pages/forums/view.js
  postcss.config.js
  store/actions/forums.js
  store/reducers/forums.js
  workers/offline.js
Labels: ✨feature

#152 Display build info in banner if in development or built from staging branch.
  .env.example
  README.md
  components/Banner.js
  scss/core/_banner.scss
Labels: ✨feature

#153 [WEB-78] Fix dropdown lists
  LAYERS.md
  scss/components/_application-nav-control.scss
  scss/components/_dropdown.scss
  scss/components/_tooltip.scss
  scss/core/_root.scss
Labels: 🐛bugfix

#155 [WEB-56] Update Next to fix absolute path compilation issues
  package.json
  yarn.lock
Labels: 🐛bugfix

#157 [WEB-38] Refactor mobile header
  components/Main.js
  components/Page.js
  components/PageHeader.js
  pages/about/index.js
  pages/about/jobs.js
  pages/about/team.js
  pages/confirmations/account-confirm.js
  pages/confirmations/email-update-confirm.js
  pages/contact.js
  pages/forgot-password.js
  pages/forums/create.js
  pages/forums/list.js
  pages/forums/view.js
  pages/groups/create.js
  pages/groups/group.js
  pages/groups/search.js
  pages/index.js
  pages/login.js
  pages/my/groups.js
  pages/register.js
  pages/reset-password.js
  pages/users/user.js
  scss/app.scss
  scss/components/_hero.scss
  scss/components/_page-header.scss
  scss/core/_banner.scss
  scss/core/_root.scss
  scss/pages/_page.scss
Labels: ✨feature

#156 [WEB-79] The "Clapton fixes all the prop problems" PR.
  components/AddressInput.js
  components/Button.js
  components/Dropdown.js
  components/GroupProfilePanels/GroupDetailsPanel.js
  components/TabPanel.js
  docker-compose.yml
  next.config.js
Labels: 🐛bugfix

#158 [WEB-38] Move nav control to page header
  components/Banner.js
  components/Page.js
  components/PageHeader.js
  scss/app.scss
  scss/components/_application-banner-control.scss
  scss/components/_application-nav-control.scss
  scss/components/_page-header.scss
  scss/core/_root.scss
Labels: ✨feature

#159 [WEB-86] [WEB-87] Fix user reducer issues
  store/actions/authentication.js
  store/reducers/users.js
Labels: 🐛bugfix

#160 [WEB-85] Session Validation, and other related things.
  components/AlertsController.js
  components/Avatar.js
  components/Forums/ForumThreadCard.js
  components/Forums/ThreadCommentCard.js
  components/Forums/ThreadCommentForm.js
  components/GroupCard.js
  components/GroupProfilePanels/GroupSettingsPanel.js
  components/Nav.js
  components/Page.js
  components/UserProfilePanels/UserSettingsPanel.js
  pages/confirmations/account-confirm.js
  pages/forgot-password.js
  pages/login.js
  pages/register.js
  pages/reset-password.js
  store.js
  store/actionCreators.js
  store/actionTypes.js
  store/actions/authentication.js
  store/initialState.js
  store/reducers/authentication.js
Labels: ☠️urgent, ✨feature, 🐛bugfix

#166 [WEB-84] Tests!
  .babelrc
  __mocks__/style.mock.js
  __tests__/_template.test.js
  __tests__/components/Avatar.test.js
  __tests__/components/Button.test.js
  __tests__/components/Component.test.js
  __tests__/components/Pagination.test.js
  __tests__/components/PasswordInput.test.js
  __tests__/components/ValidatedInput.test.js
  components/Avatar.js
  components/Button.js
  components/Pagination.js
  components/PasswordInput.js
  components/ValidatedInput.js
  jest.config.js
  package.json
  yarn.lock
Labels: ✨feature

#163 [WEB-89] Fix alert card z-index
  scss/components/_alert-card.scss
Labels: 🐛bugfix

#164 [WEB-93] [WEB-94] Fix conditional rendering blocks in forums and forum threads
  pages/forums/list.js
  pages/forums/view.js
Labels: 🐛bugfix

#165 [WEB-90] Add placeholder text for group cards on user profiles.
  pages/users/user.js
Labels: 🐛bugfix

#167 [WEB-95] Add proper validation for usernames
  pages/register.js
Labels: 🐛bugfix

#169 [WEB-72] Dialog Wrapper
  .vscode/launch.json
  LAYERS.md
  __tests__/_testHelpers/containers.js
  __tests__/_testHelpers/index.js
  __tests__/components/Avatar.test.js
  __tests__/components/DialogWrapper.test.js
  components/Avatar.js
  components/AvatarUploaderDialog.js
  components/DialogWrapper.js
  package.json
  scss/app.scss
  scss/components/_alert-card.scss
  scss/components/_avatar-uploader-dialog.scss
  scss/core/_dialog.scss
  scss/core/_root.scss
Labels: ✨feature

#170 Add ZenDesk widget support
  components/Banner.js
  components/Nav.js
  helpers/activateZenDesk.js
  helpers/index.js
  pages/_document.js
  pages/confirmations/account-confirm.js
  pages/confirmations/email-update-confirm.js
  pages/forgot-password.js
  pages/register.js
  pages/reset-password.js
  scss/core/_button.scss
Labels: ⚙️task

#171 [WEB-96] Markdown in forums
  .gitignore
  README.md
  __tests__/components/Dialog.test.js
  __tests__/components/DialogWrapper.test.js
  __tests__/components/Pagination.test.js
  components/AlertCard.js
  components/Avatar.js
  components/AvatarUploaderDialog.js
  components/Button.js
  components/Dialog.js
  components/DialogWrapper.js
  components/EditorHelpDialog.js
  components/Forums/ForumThreadCard.js
  components/Forums/ThreadCommentCard.js
  components/Forums/ThreadCommentForm.js
  components/Page.js
  package.json
  pages/_document.js
  pages/forums/view.js
  scss/app.scss
  scss/components/_avatar-uploader-dialog.scss
  scss/components/_avatar.scss
  scss/components/_card-list.scss
  scss/components/_forum-thread-card.scss
  scss/core/_dialog.scss
  scss/core/_menu.scss
  scss/core/_pre.scss
  scss/core/_root.scss
  scss/lib.scss
  yarn.lock
Labels: 🐛bugfix

#168 Remove authentication from group search
  components/AvatarUploaderDialog.js
  components/Dialog.js
  components/EditorHelpDialog.js
  components/PasswordInput.js
  components/RegistrationDialog.js
  components/ValidatedInput.js
  package.json
  pages/groups/group.js
  pages/groups/search.js
  pages/login.js
  scss/app.scss
  scss/components/_input-group.scss
  scss/components/_password-input.scss
  scss/core/_button.scss
  scss/core/_dialog.scss
  scss/core/_input.scss
  scss/core/_menu.scss
  scss/core/_root.scss
  scss/variables/_disabled.scss
Labels: ☠️urgent

#175 [WEB-91] Link tab panels on user profiles
  .circleci/config.yml
  components/TabPanel.js
  jest.config.js
  pages/users/user.js
  routes.js
Labels: ✨feature

#177 [WEB-91] Navigation updates
  components/Nav.js
  components/Page.js
  pages/users/user.js
  routes.js
  scss/core/_banner.scss
Labels: ✨feature

#178 [WEB-92][WEB-100] Link group tabs
  components/Page.js
  pages/groups/group.js
  pages/users/user.js
  routes.js
Labels: ✨feature, 🐛bugfix

#181 fix(GroupProfile): remove placeholder 'new event' button.
  pages/groups/group.js
Labels: ☠️urgent, ⚙️task
