Repository RollForGuild/rollforguild.com, pull requests merged in 2018-03, with the labels that each got.

#87 Global state deep merging.
  helpers/deepMergeJSONAPIObjectCollections.js
  store/reducers/groups.js
  store/reducers/users.js
Labels: enhancement

#89 fix(Dropdown): Fix shrinking dropdowns
  scss/components/_dropdown.scss
  scss/components/_input-group.scss
Labels: bug

#88 [WEB-9][WEB-10] Allow users to change group settings
  components/GroupProfilePanels/GroupSettingsPanel.js
  components/ValidatedInput.js
  helpers/convertStringToSlug.js
  pages/groups/create.js
  pages/groups/group.js
  scss/animations/_pulse.scss
  scss/app.scss
  scss/components/_validated-input.scss
  store/actionTypes.js
  store/actions/groups.js
Labels: enhancement

#90 Beta updates
  components/Header.js
  scss/components/_brand.scss
  scss/core/_banner.scss
Labels: enhancement

#91 feat(Nav): Make nav responsive
  components/Banner.js
  components/Page.js
  pages/_document.js
  scss/app.scss
  scss/components/_application-nav-control.scss
  scss/core/_banner.scss
  scss/core/_input.scss
  scss/core/_root.scss
  scss/pages/_home.scss
  scss/pages/_page.scss
Labels: enhancement

#97 [WEB-27] chore(*): Add hreflang tag
  pages/_document.js
Labels: enhancement

#96 [WEB-14] Bug reporting link
  components/Banner.js
  components/Header.js
  scss/core/_banner.scss
Labels: enhancement

#95 [WEB-26] chore(Nav): Hide superfluous links
  components/Nav.js
Labels: enhancement

#98 [WEB-6] Redirect unauthenticated users from authenticated pages
  components/Page.js
  pages/character-builder.js
  pages/character.js
  pages/groups/search.js
  pages/login.js
  pages/logout.js
  pages/my/account.js
  pages/my/character.js
  pages/my/characters.js
  pages/my/groups.js
  pages/my/profile.js
  pages/users/edit.js
  pages/users/user.js
Labels: bug

#99 fix(*): Move eslint out of devDependencies
  package.json
Labels: bug

#100 Release 1.2.0
  components/Banner.js
  components/Header.js
  components/Nav.js
  components/Page.js
  package.json
  pages/_document.js
  pages/character-builder.js
  pages/character.js
  pages/groups/search.js
  pages/login.js
  pages/logout.js
  pages/my/account.js
  pages/my/character.js
  pages/my/characters.js
  pages/my/groups.js
  pages/my/profile.js
  pages/users/edit.js
  pages/users/user.js
  scss/core/_banner.scss
Labels: enhancement

#101 [WEB-35] Prevent null reduxOptions from breaking shit
  components/Page.js
Labels: ☠️urgent

#102 [WEB-35] Fix the null error for real this time
  components/Page.js
Labels: ☠️urgent

#103 Release 1.2.1
  components/Page.js
Labels: release, ☠️urgent

#110 [WEB-20] Enable group discoverability setting
  components/GroupProfilePanels/GroupSettingsPanel.js
Labels: ✨feature

#111 [WEB-7] [WEB-8] Password Input
  components/Page.js
  components/PasswordInput.js
  components/UserProfilePanels/UserSettingsPanel.js
  components/ValidatedInput.js
  scss/app.scss
  scss/colors/_orange.scss
  scss/components/_password-input.scss
  scss/components/_validated-input.scss
Labels: ✨feature

#116 [WEB-19] Group sharing
  components/AvatarUploaderDialog.js
  components/GroupProfilePanels/GroupDetailsPanel.js
  components/GroupProfilePanels/GroupSettingsPanel.js
  components/Head.js
  components/Page.js
  components/ShareableLink.js
  components/Tooltip.js
  helpers/convertSlugToUUID.js
  helpers/index.js
  helpers/isUUID.js
  package.json
  pages/_document.js
  pages/groups/create.js
  pages/groups/group.js
  pages/groups/search.js
  pages/logout.js
  scss/app.scss
  scss/components/_input-group.scss
  scss/components/_tooltip.scss
  scss/core/_button.scss
  services/api.js
  store/actions/groups.js
  store/reducers/groups.js
  store/reducers/rulesets.js
  store/reducers/users.js
  workers/offline.js
  yarn.lock
Labels: ✨feature

#108 [WEB-22] Password reset
  components/Page.js
  pages/forgot-password.js
  pages/login.js
  pages/reset-password.js
  routes.js
  scss/core/_button.scss
  store/actionTypes.js
  store/actions/authentication.js
Labels: ✨feature

#118 fix(*): Add support for local API environment variable
  services/api.js
Labels: ☠️urgent

#120 fix(*): Add build specific env vars
  .circleci/config.yml
Labels: ☠️urgent

#121 Release 1.3.0
  .circleci/config.yml
  components/AvatarUploaderDialog.js
  components/Banner.js
  components/GroupCard.js
  components/GroupProfilePanels/GroupDetailsPanel.js
  components/GroupProfilePanels/GroupSettingsPanel.js
  components/Head.js
  components/Nav.js
  components/Page.js
  components/PasswordInput.js
  components/ShareableLink.js
  components/Tooltip.js
  components/UserProfilePanels/UserSettingsPanel.js
  components/ValidatedInput.js
  helpers/convertSlugToUUID.js
  helpers/index.js
  helpers/isUUID.js
  next.config.js
  package.json
  pages/_document.js
  pages/character-builder.js
  pages/forgot-password.js
  pages/groups/create.js
  pages/groups/group.js
  pages/groups/search.js
  pages/login.js
  pages/logout.js
  pages/my/characters.js
  pages/my/groups.js
  pages/register.js
  pages/reset-password.js
  pages/users/edit.js
  pages/users/user.js
  routes.js
  scss/app.scss
  scss/colors/_orange.scss
  scss/components/_avatar-uploader-dialog.scss
  scss/components/_avatar.scss
  scss/components/_card.scss
  scss/components/_error-box.scss
  scss/components/_input-group.scss
  scss/components/_password-input.scss
  scss/components/_profile.scss
  scss/components/_settings-panel.scss
  scss/components/_tooltip.scss
  scss/components/_validated-input.scss
  scss/core/_button.scss
  scss/core/_strong.scss
  scss/pages/_edit-profile.scss
  scss/pages/_user-profile.scss
  services/api.js
  store/actionTypes.js
  store/actions/authentication.js
  store/actions/groups.js
  store/actions/users.js
  store/reducers/groups.js
  store/reducers/rulesets.js
  store/reducers/users.js
  workers/offline.js
  yarn.lock
Labels: release

#124 [WEB-19] Group sharing
  components/GroupProfilePanels/GroupDetailsPanel.js
  pages/_document.js
  pages/groups/group.js
  scss/app.scss
  scss/core/_lists.scss
  scss/core/_section.scss
Labels: ✨feature

#127 [WEB-43] Convert all inputs to validated inputs
  components/PasswordInput.js
  components/SimpleDropdown.js
  components/ValidatedInput.js
  pages/forgot-password.js
  pages/groups/create.js
  pages/login.js
  pages/register.js
  pages/reset-password.js
Labels: ✨feature

#126 [WEB-17] Add analytics for links and buttons
  components/Banner.js
  components/Button.js
  components/Form.js
  components/GroupCard.js
  components/GroupProfilePanels/GroupDetailsPanel.js
  components/GroupProfilePanels/GroupSettingsPanel.js
  components/Head.js
  components/Link.js
  components/Nav.js
  components/Pagination.js
  components/TabPanel.js
  components/TrackableComponent.js
  components/UserProfilePanels/UserSettingsPanel.js
  helpers/index.js
  helpers/pushTrackableEventToDataLayer.js
  pages/_document.js
  pages/forgot-password.js
  pages/groups/create.js
  pages/groups/group.js
  pages/groups/search.js
  pages/login.js
  pages/my/characters.js
  pages/my/groups.js
  pages/register.js
  pages/reset-password.js
  pages/users/user.js
  routes.js
  scss/components/_application-nav-control.scss
  scss/components/_card.scss
  scss/components/_pagination.scss
  scss/core/_headings.scss
  scss/lib/_nprogress.scss
Labels: ✨feature

#129 [WEB-12] Enable user email updating
  components/UserProfilePanels/UserSettingsPanel.js
Labels: ✨feature

#130 [WEB-18] Make search field more mobile friendly
  components/ValidatedInput.js
  pages/groups/search.js
  scss/components/_dropdown.scss
  scss/components/_input-group.scss
  scss/components/_tooltip.scss
  scss/core/_button.scss
  scss/core/_fieldset.scss
Labels: ✨feature

#132 [WEB-60] Don't activate show password button on return key
  components/Dropdown.js
  components/PasswordInput.js
  pages/groups/search.js
Labels: ☠️urgent

#135 [WEB-48] [WEB-51] Add basis for forums
  components/Forums/ForumThreadCard.js
  components/Nav.js
  pages/forums/create.js
  pages/forums/list.js
  pages/forums/view.js
  routes.js
  scss/app.scss
  scss/components/_forum-thread-card.scss
  store.js
  store/actionTypes.js
  store/actions/threads.js
  store/initialState.js
  store/reducers/index.js
  store/reducers/threads.js
  store/reducers/users.js
Labels: ✨feature

#133 [WEB-12] email confirmation pages
  .eslintrc.json
  components/Avatar.js
  components/AvatarUploaderDialog.js
  components/Page.js
  helpers/deepMergeJSONAPIObjectCollections.js
  pages/_document.js
  pages/confirmations/account-confirm.js
  pages/confirmations/email-update-confirm.js
  pages/groups/group.js
  routes.js
  store/actionTypes.js
  store/actions/authentication.js
Labels: ✨feature

#134 [WEB-2] Link maps to directions on Google Maps
  components/StaticMap.js
  pages/groups/group.js
  scss/components/_profile.scss
  scss/components/_static-map.scss
Labels: ✨feature

#139 [WEB-55] Store Alerts
  components/AlertCard.js
  components/AlertsController.js
  components/Forums/ThreadCommentForm.js
  components/Page.js
  helpers/createAlertObject.js
  helpers/index.js
  pages/forums/view.js
  scss/app.scss
  scss/components/_alert-card.scss
  scss/components/_card.scss
  store.js
  store/actionCreators.js
  store/actionTypes.js
  store/actions/alerts.js
  store/actions/forums.js
  store/initialState.js
  store/reducers/alerts.js
  store/reducers/index.js
Labels: ✨feature

#140 [WEB-54] Add the About page
  components/Hero.js
  components/Markdown.js
  pages/about/index.js
  pages/about/team.js
  pages/index.js
  scss/app.scss
  scss/components/_hero.scss
  scss/pages/_home.scss
  scss/pages/_page.scss
Labels: ✨feature

#141 [WEB-75] Temporary patch for loggedIn check
  store.js
Labels: ☠️urgent

#143 [WEB-76] Display group admin UI to group owners
  pages/groups/group.js
Labels: ☠️urgent

#144 [WEB-65] Notify users to confirm their new email when changing it.
  components/UserProfilePanels/UserSettingsPanel.js
  pages/users/user.js
Labels: ✨feature
