Repository RollForGuild/rollforguild.com, pull requests merged in 2018-05, with the labels that each got.

#180 [WEB-69] [WEB-70] [WEB-71] The rest of EventsV1
  components/GameInput.js
  components/Groups/GroupEventCard.js
  components/Groups/GroupEventEditDialog.js
  components/Groups/GroupEventsPanel.js
  helpers/formatGameString.js
  helpers/index.js
  pages/groups/group.js
  routes.js
  scss/components/_card.scss
  store/actionTypes.js
  store/actions/events.js
  store/initialState.js
  store/reducers/events.js
  store/reducers/games.js
  store/reducers/index.js
Labels: ✨feature

#183 Fix events by using global state to track event objects.
  components/Groups/GroupEventsPanel.js
  pages/groups/group.js
  store/reducers/events.js
Labels: ☠️urgent, 🐛bugfix

#185 Release v1.6.1
  components/TabPanel.js
  scss/variables/_disabled.scss
Labels: ☠️urgent, 🐛bugfix

#187 Fix event delete button
  components/Groups/GroupEventCard.js
  components/Groups/GroupEventsPanel.js
Labels: ☠️urgent, 🐛bugfix

#186 Merge hotfix to dev
  components/TabPanel.js
  scss/variables/_disabled.scss
Labels: 🐛bugfix

#191 [WEB-110] Convert rsync install to Alpine syntax
  .circleci/config.yml
Labels: 🐛bugfix

#192 [WEB-115] Improve page title handling
  components/Head.js
  components/Page.js
  components/PageDescription.js
  components/PageTitle.js
  pages/about/index.js
  pages/about/team.js
  pages/character-builder.js
  pages/character.js
  pages/confirmations/account-confirm.js
  pages/confirmations/email-update-confirm.js
  pages/contact.js
  pages/forgot-password.js
  pages/forums/list.js
  pages/forums/view.js
  pages/gm/dungeons.js
  pages/gm/encounters.js
  pages/gm/monsters.js
  pages/gm/npcs.js
  pages/gm/treasure.js
  pages/groups/create.js
  pages/groups/group.js
  pages/groups/search.js
  pages/index.js
  pages/login.js
  pages/logout.js
  pages/my/character.js
  pages/my/characters.js
  pages/my/groups.js
  pages/privacy-policy.js
  pages/register.js
  pages/reset-password.js
  pages/roadmap.js
  pages/terms-and-conditions.js
  pages/users/user.js
Labels: ⚙️task

#193 [WEB-115] Add proxy for Wordpress pages
  pages/about/index.js
  pages/wordpress-proxy.js
  server/config/router.js
Labels: ✨feature

#195 [WEB-88] Optimize profiles for mobile
  components/PageDescription.js
  components/PageTitle.js
  components/TabPanel.js
  components/ValidatedInput.js
  jest.config.js
  scss/components/_dropdown.scss
  scss/components/_profile.scss
  scss/components/_tab-panel.scss
  scss/components/_validated-input.scss
Labels: ✨feature

#194 Release v1.8.0
  .circleci/config.yml
  .gitignore
  Dockerfile
  README.md
  components/Head.js
  components/Page.js
  components/PageDescription.js
  components/PageTitle.js
  components/TabPanel.js
  components/ValidatedInput.js
  docker-compose.yml
  jest.config.js
  package.json
  pages/about/index.js
  pages/about/team.js
  pages/character-builder.js
  pages/character.js
  pages/confirmations/account-confirm.js
  pages/confirmations/email-update-confirm.js
  pages/contact.js
  pages/forgot-password.js
  pages/forums/list.js
  pages/forums/view.js
  pages/gm/dungeons.js
  pages/gm/encounters.js
  pages/gm/monsters.js
  pages/gm/npcs.js
  pages/gm/treasure.js
  pages/groups/create.js
  pages/groups/group.js
  pages/groups/search.js
  pages/index.js
  pages/login.js
  pages/logout.js
  pages/my/character.js
  pages/my/characters.js
  pages/my/groups.js
  pages/privacy-policy.js
  pages/register.js
  pages/reset-password.js
  pages/roadmap.js
  pages/terms-and-conditions.js
  pages/users/user.js
  pages/wordpress-proxy.js
  scss/components/_dropdown.scss
  scss/components/_profile.scss
  scss/components/_tab-panel.scss
  scss/components/_validated-input.scss
  server/config/router.js
  yarn.lock
Labels: 📦release

#196 fix: Typo in prod deploy
  .circleci/config.yml
Labels: ☠️urgent, 🐛bugfix

#197 Hotfix/fix circle config for prod deploy
  .circleci/config.yml
Labels: ⚙️task

#199 Release v1.8.1
  server/config/router.js
Labels: 📦release

#201 Restore offline worker script
  .gitignore
  static/sw.js
Labels: 🐛bugfix

#202 Release v1.8.2
  .gitignore
  components/Head.js
  static/sw.js
Labels: 📦release

#203 Remove the sitemap generator as it was causing all kinds of issues
  package.json
  pages/privacy-policy.js
  pages/wordpress-proxy.js
  server/config/router.js
  server/server.js
  yarn.lock
Labels: 🐛bugfix

#204 Release v1.8.3
  package.json
  pages/privacy-policy.js
  pages/wordpress-proxy.js
  server/config/router.js
  server/server.js
  yarn.lock
Labels: 🐛bugfix, 📦release

#205 Fix Forum Thread create form
  pages/forums/create.js
  routes.js
Labels: ☠️urgent, 🐛bugfix

#206 Release v1.8.4
  pages/forums/create.js
  routes.js
Labels: ☠️urgent, 🐛bugfix, 📦release

#207 Dependency updates and migrations
  __tests__/components/Component.test.js
  __tests__/components/Dialog.test.js
  __tests__/components/Pagination.test.js
  __tests__/components/PasswordInput.test.js
  __tests__/components/ValidatedInput.test.js
  components/AlertCard.js
  components/Banner.js
  components/Dialog.js
  components/Forums/ForumThreadCard.js
  components/Forums/ThreadCommentCard.js
  components/Forums/ThreadCommentForm.js
  components/Groups/GroupDetailsPanel.js
  components/Groups/GroupEventCard.js
  components/Groups/GroupEventCreateDialog.js
  components/Groups/GroupEventEditDialog.js
  components/Groups/GroupSettingsPanel.js
  components/Nav.js
  components/Page.js
  components/PageHeader.js
  components/PasswordInput.js
  components/RegistrationDialog.js
  components/ShareableLink.js
  components/UserProfilePanels/UserSettingsPanel.js
  components/ValidatedInput.js
  helpers/faIconLibrary.js
  package.json
  pages/forgot-password.js
  pages/groups/group.js
  pages/groups/search.js
  pages/login.js
  pages/my/characters.js
  pages/register.js
  pages/reset-password.js
  scss/lib.scss
  static/sw.js
  yarn.lock
Labels: ⚙️task

#209 [WEB-116] Remove bottom margins from h1s in page headers
  scss/components/_page-header.scss
  scss/core/_dialog.scss
Labels: 🐛bugfix

#210 [WEB-126] Convert group descriptions to Markdown
  components/Groups/GroupDetailsPanel.js
  pages/groups/create.js
  pages/groups/group.js
Labels: ⚙️task

#211 [WEB-143] Add Markdown help dialog to thread creation page
  components/Forums/ThreadCommentForm.js
  components/MarkdownHelpButton.js
  pages/forums/create.js
Labels: ⚙️task

#215 [WEB-117] Auto shorten group descriptions for page meta
  pages/groups/group.js
Labels: ⚙️task

#214 [WEB-102] Remove beta tag from brand
  scss/components/_brand.scss
Labels: ⚙️task

#213 [WEB-108] Fix forum comment header formatting
  components/Forums/ThreadCommentCard.js
Labels: 🐛bugfix

#212 [WEB-112] Fix text for group event alerts
  store/actions/events.js
Labels: 🐛bugfix

#216 Release v1.8.5
  __tests__/components/Component.test.js
  __tests__/components/Dialog.test.js
  __tests__/components/Pagination.test.js
  __tests__/components/PasswordInput.test.js
  __tests__/components/ValidatedInput.test.js
  components/AlertCard.js
  components/Banner.js
  components/Dialog.js
  components/Forums/ForumThreadCard.js
  components/Forums/ThreadCommentCard.js
  components/Forums/ThreadCommentForm.js
  components/Groups/GroupDetailsPanel.js
  components/Groups/GroupEventCard.js
  components/Groups/GroupEventCreateDialog.js
  components/Groups/GroupEventEditDialog.js
  components/Groups/GroupSettingsPanel.js
  components/MarkdownHelpButton.js
  components/Nav.js
  components/Page.js
  components/PageHeader.js
  components/PasswordInput.js
  components/RegistrationDialog.js
  components/ShareableLink.js
  components/UserProfilePanels/UserSettingsPanel.js
  components/ValidatedInput.js
  helpers/faIconLibrary.js
  package.json
  pages/forgot-password.js
  pages/forums/create.js
  pages/groups/create.js
  pages/groups/group.js
  pages/groups/search.js
  pages/login.js
  pages/my/characters.js
  pages/register.js
  pages/reset-password.js
  scss/components/_brand.scss
  scss/components/_page-header.scss
  scss/core/_dialog.scss
  scss/lib.scss
  static/sw.js
  store/actions/events.js
  yarn.lock
Labels: 📦release

#218 Release v1.8.6
  components/Page.js
  scss/lib.scss
Labels: 📦release

#222 [WEB-113] Fix modal clipping dropdown options
  components/Component.js
  components/Dropdown.js
  components/PasswordInput.js
  components/ValidatedInput.js
  scss/components/_dropdown.scss
  scss/core/_dialog.scss
Labels: 🐛bugfix

#223 [WEB-147] Next 6 upgrade & migration
  .babelrc
  .eslintrc.json
  components/AppLayout.js
  components/AvatarUploaderDialog.js
  components/Banner.js
  components/GameInput.js
  components/Groups/GroupDetailsPanel.js
  components/Groups/GroupEventCard.js
  components/Groups/GroupSettingsPanel.js
  components/Link.js
  components/Nav.js
  components/Page.js
  components/TrackableComponent.js
  helpers/connect.js
  helpers/index.js
  package.json
  pages/_app.js
  pages/_document.js
  pages/confirmations/account-confirm.js
  pages/confirmations/email-update-confirm.js
  pages/forgot-password.js
  pages/groups/create.js
  pages/groups/group.js
  pages/groups/search.js
  pages/register.js
  pages/reset-password.js
  pages/users/user.js
  scss/core/_banner.scss
  store/actionCreators.js
  store/actions/alerts.js
  store/actions/authentication.js
  store/initialState.js
  store/reducers/authentication.js
  store/reducers/events.js
  store/reducers/forums.js
  store/reducers/games.js
  store/reducers/groups.js
  store/reducers/rulesets.js
  store/reducers/users.js
  yarn.lock
Labels: ⚙️task

#225 [WEB-136] [WEB-137] [WEB-138] [WEB-139] a11y improvements
  components/Avatar.js
  components/Banner.js
  components/Nav.js
  components/PasswordInput.js
  pages/groups/search.js
Labels: ⚙️task
